@baseUR = https://vinicius.pro.br/daoo/rest/index.php


# Contact
# Create
POST {{baseUrl}}/contacts HTTP/1.1
Content-Type: application/json

{
  "name": "Bruno Angst",
  "email": "mbcangst2@gmail.com",
}
###

# Create
GET {{baseUrl}}/contacts/view HTTP/1.1
Content-Type: application/json

###